config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  # Page format:
  # get '/url', to: 'controller#action'
  # I think the default action is go to the view.
  # To link to a page, use <url>_path
  root 'users#loginmenu'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users #defines a whole bunch of routes for a fully RESTful API

  # In future

  # For edit details page, url should be the username
  
  # get '/timesheet', to: 'timesheet#form' # or something similar
  # post '/timesheet', to: ???

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  before_save { username.downcase! }
  validates :name, presence: true, length: { maximum: 50 }, 
            uniqueness: {case_sensitive: false}
  validates :email, presence: true, length: { maximum: 100 }, 
            uniqueness: {case_sensitive: false}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Welcome back, #{user.name}!"
      redirect_to user # change this later, when users are created by admins
    else
      flash.now[:danger] = "Incorrect login."
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url # may have to remove this later too.
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # The following are routed to by 'resources :users'

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "New user created."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end






  def login
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    Jesse's Timesheet App
  </small>
<!--   <nav>
    <ul>
      <li>Future link</li>
      <li>Future link 2</li>
      <li>Future link 3</li>
    </ul>
  </nav> -->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Home", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Future link", '#' %></li>
        <li><%= link_to "Future link 2", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "My Details", current_user %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timesheets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/login.html.erb
<h1>Log in</h1>
<p>
  This is the official log in page.
</p>

app/views/users/loginmenu.html.erb
<h1>Timesheets - Login Menu</h1>
<p>
  The current time is: <%= Time.now %>
</p>
<%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form_control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form_control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form_control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form_control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form_control' %>

      <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!-- This is routed to by 'resources :users' -->
<h1>Dashboard</h1>
<p>You are:
<%= @user.name %>, <%= @user.email %>
</p>